# ==============================
# TONAL
# ==============================

tonal:
  n_samples: 50000

# ==============================
# VOCAL
# ==============================

vocal:
  n_samples: 50000