env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Installer
        run: |
          pip install -r requirements.txt pytest pytest-cov
          pip install -e .
      - name: Lancer les tests
        # Le PYTHONPATH=. permet à pytest de trouver "app.py" et "gain_project"
        run: PYTHONPATH=. pytest tests/ -v